name: CI build and publish

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'pom.xml'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'pom.xml'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven build
        run: ./mvnw -B -U -T 1C clean install
      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: ./mvnw -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build error artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: |
            target/surefire-reports/
            target/*.log
